CREATE TABLE debts
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creditor_id          BIGINT        NOT NULL REFERENCES users (id),
    debtor_id            BIGINT        NOT NULL REFERENCES users (id),
    title                VARCHAR(200)  NOT NULL,
    description          VARCHAR(1000),
    method               VARCHAR(20)   NOT NULL CHECK (method IN ('INSTALLMENT', 'OPEN', 'FULL')),
    principal_amount     NUMERIC(14,2) NOT NULL,
    installment_count    INT,
    installment_amount   NUMERIC(14,2),
    start_date           DATE          NOT NULL,
    status               VARCHAR(20)   NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PARTIAL', 'PAID', 'CANCELLED')),
    paid_amount          NUMERIC(14,2) NOT NULL DEFAULT 0,
    paid_at              TIMESTAMP,
    sort_order           INT,
    created_at           TIMESTAMP     NOT NULL DEFAULT now(),
    updated_at           TIMESTAMP     NOT NULL DEFAULT now()
);

CREATE INDEX ix_debts_creditor_id ON debts (creditor_id);
CREATE INDEX ix_debts_debtor_id ON debts (debtor_id);
CREATE INDEX ix_debts_status ON debts (status);

CREATE TABLE installments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_id   BIGINT        NOT NULL REFERENCES debts (id) ON DELETE CASCADE,
    no        INT           NOT NULL,
    amount    NUMERIC(14,2) NOT NULL,
    kind      VARCHAR(20)   NOT NULL DEFAULT 'PRINCIPAL' CHECK (kind IN ('PRINCIPAL', 'INTEREST')),
    status    VARCHAR(20)   NOT NULL DEFAULT 'UNPAID' CHECK (status IN ('UNPAID', 'PAID')),
    due_date  DATE          NOT NULL,
    pay_date  DATE,
    paid_at   TIMESTAMP
);

CREATE UNIQUE INDEX ux_installments_debt_no ON installments (debt_id, no);

CREATE TABLE open_loan_records
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debt_id              BIGINT        NOT NULL REFERENCES debts (id) ON DELETE CASCADE,
    no                   INT           NOT NULL,
    pay_date             DATE          NOT NULL,
    total_paid           NUMERIC(14,2) NOT NULL DEFAULT 0,
    interest             NUMERIC(14,2) NOT NULL DEFAULT 0,
    remaining_principal  NUMERIC(14,2) NOT NULL,
    status               VARCHAR(20)   NOT NULL DEFAULT 'UNPAID' CHECK (status IN ('UNPAID', 'PAID')),
    paid_at              TIMESTAMP
);

CREATE UNIQUE INDEX ux_open_loan_records_debt_no ON open_loan_records (debt_id, no);
