ALTER TABLE users RENAME COLUMN avatar_key TO avatar_public_id;
ALTER TABLE users ADD COLUMN avatar_url VARCHAR(500);

CREATE TABLE bank_accounts
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creditor_id   BIGINT       NOT NULL UNIQUE REFERENCES users (id),
    bank_name     VARCHAR(100) NOT NULL,
    account_no    VARCHAR(30)  NOT NULL,
    account_name  VARCHAR(150) NOT NULL,
    payment_note  VARCHAR(255),
    updated_at    TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE TABLE slips
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    debtor_id           BIGINT       NOT NULL REFERENCES users (id),
    creditor_id         BIGINT       NOT NULL REFERENCES users (id),
    public_id           VARCHAR(255) NOT NULL,
    secure_url          VARCHAR(500) NOT NULL,
    original_filename   VARCHAR(255) NOT NULL,
    format              VARCHAR(20),
    resource_type       VARCHAR(20)  NOT NULL DEFAULT 'image',
    bytes               BIGINT       NOT NULL CHECK (bytes <= 1048576),
    uploaded_at         TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX ix_slips_debtor_creditor_uploaded ON slips (debtor_id, creditor_id, uploaded_at DESC);

CREATE TABLE documents
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_creditor_id   BIGINT REFERENCES users (id),
    debtor_id           BIGINT REFERENCES users (id),
    title               VARCHAR(255) NOT NULL,
    public_id           VARCHAR(255) NOT NULL,
    secure_url          VARCHAR(500) NOT NULL,
    original_filename   VARCHAR(255) NOT NULL,
    format              VARCHAR(20),
    resource_type       VARCHAR(20)  NOT NULL DEFAULT 'raw',
    bytes               BIGINT       NOT NULL,
    uploaded_by         BIGINT       NOT NULL REFERENCES users (id),
    uploaded_at         TIMESTAMP    NOT NULL DEFAULT now()
);

CREATE INDEX ix_documents_owner_creditor ON documents (owner_creditor_id);
CREATE INDEX ix_documents_debtor ON documents (debtor_id);
